export default {
  pages: [
    'pages/index/index',
    'pages/button/index',
    'pages/form/index',
    'pages/form/form-page/index',
    'pages/form/form-input-status/index',
    'pages/form/form-vcode/index',
    'pages/form/form-checkbox/index',
    'pages/form/form-access/index',
    'pages/form/form-radio/index',
    'pages/form/form-switch/index',
    'pages/form/form-select/index',
    'pages/form/form-select-primary/index',
    'pages/form/form-textarea/index',
    'pages/list/index',
    'pages/slider/index',
    'pages/uploader/index',
    'pages/article/index',
    'pages/badge/index',
    'pages/flex/index',
    'pages/footer/index',
    'pages/gallery/index',
    'pages/grid/index',
    'pages/icons/index',
    'pages/loading/index',
    'pages/loadmore/index',
    'pages/panel/index',
    'pages/preview/index',
    'pages/progress/index',
    'pages/search/index',
    'pages/navbar/index',
    'pages/tabbar/index',
    'pages/actionsheet/index',
    'pages/dialog/index',
    'pages/half-screen-dialog/index',
    'pages/msg/index',
    'pages/picker/index',
    'pages/toast/index',
    'pages/top-tips/index',
    'pages/msg/success/index',
    'pages/msg/warn/index',
    'pages/msg/text/index',
    'pages/msg/text-primary/index',
    'pages/msg/area-preview/index',
    'pages/msg/area-tips/index',
    'pages/msg/area-cell/index',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#fff',
    navigationBarTitleText: 'Taro模版',
    navigationBarTextStyle: 'black',
  },
}
