export { default as uploadType } from './typeSync/fetch2remote'
export { default as rapper } from './rapper'
export { default as defineConfig } from './typeSync/mergeOptions'
export { default as typeUpload } from './typeSync/type2remote'
export { deleteTag } from './typeSync/type2remote'
